### PR TITLE
4.0 release, memory leaks fixes

### LINKED ISSUE #36: Memory leak when starting/stopping scanning
Hey there,

first of all thanks for making this awesome API. I really enjoy working with it. 

Unfortunately I receive memory leaks when turning scanning on and off. First I thought it´s a problem in my application but then I tried the provided example project and the problem also exists there.

Configuration:
iPhone 6 Plus
iOS 9.3.1
RxBluetoothKit 1.2.0

Steps:
1) Start RxBluetoothKit example project with simulator (Leaks)
2) Repeat turning scanning On/Off. (I switched it around every 5 secons)
3) Wait for leak to come

If you need any further info then don´t hesitate to ask. ;-)

Can you tell where this leak is coming from?

Thanks a lot!
Regards
Philipp

### LINKED ISSUE #156: BluetoothManager deinit
Hi, guys. There are retain cycle issues in `BluetoothManager`. For example:
```
    let disposeBag = DisposeBag()
    var manager: BluetoothManager?
    
    @IBAction func action(_ sender: UIButton) {
        if manager == nil {
            manager = BluetoothManager()
            manager?.rx_state.filter { $0 == .poweredOn }.debug().subscribe().disposed(by: disposeBag)
        } else {
            manager = nil
        }
    }
```
Steps:
- tap to the button and turn bluetooth on
```
2017-10-12 16:13:50.482: TestViewController.swift:21 (action) -> subscribed
2017-10-12 16:13:50.482: TestViewController.swift:21 (action) -> Event next(poweredOn)
```
- tap again, now `manager = nil` but deinit never called
- tap again, create new manager instance
```
2017-10-12 16:19:11.940: TestViewController.swift:21 (action) -> subscribed
2017-10-12 16:19:11.956: TestViewController.swift:21 (action) -> Event next(poweredOn)
```
- turn bluetooth off and on, `(action) -> Event next(poweredOn)` print twice which is not ok
```
2017-10-12 16:21:16.438: TestViewController.swift:21 (action) -> Event next(poweredOn)
2017-10-12 16:21:16.438: TestViewController.swift:21 (action) -> Event next(poweredOn)
```

Proposed solution
https://github.com/Polidea/RxBluetoothKit/blob/master/Source/BluetoothManager.swift#L211
```
    public var rx_state: Observable<BluetoothState> {
        return .deferred { [unowned self] in
            return self.centralManager.rx_didUpdateState.startWith(self.centralManager.state)
        }
    }
```
or
```
    public var rx_state: Observable<BluetoothState> {
        return .deferred { [central = self.centralManager] in
            return central.rx_didUpdateState.startWith(central.state)
        }
    }
```

### PR DESCRIPTION
**Pull request by Kacper20**
Fixes #156 , final preparation for official 4.0 release

### CODE REVIEW

File: Source/BluetoothManager.swift [hunk 1]
```diff
@@ -270,11 +283,12 @@ public class BluetoothManager {
     /// - returns: Observable which emits retrieved `Peripheral`s. They are in connected state and contain all of the
     /// `Service`s with UUIDs specified in the `serviceUUIDs` parameter. Just after that complete event is emitted
     public func retrieveConnectedPeripherals(withServices serviceUUIDs: [CBUUID]) -> Observable<[Peripheral]> {
-        let observable = Observable<[Peripheral]>.deferred {
-            return self.centralManager.retrieveConnectedPeripherals(withServices: serviceUUIDs)
+        let observable = Observable<[Peripheral]>.deferred { [weak self] in
+            guard let strongSelf = self else { throw BluetoothError.destroyed }
+            return strongSelf.centralManager.retrieveConnectedPeripherals(withServices: serviceUUIDs)
                 .map { (peripheralTable: [RxPeripheralType]) ->
```
Comment (Cierpliwy) [inline Source/BluetoothManager.swift]: strongSelf will be locked during `retrieveConnectedPeripherals` ??

File: Source/BluetoothManager.swift [hunk 2]
```diff
@@ -285,11 +299,12 @@ public class BluetoothManager {
...
     public func retrievePeripherals(withIdentifiers identifiers: [UUID]) -> Observable<[Peripheral]> {
-        let observable = Observable<[Peripheral]>.deferred {
-            return self.centralManager.retrievePeripherals(withIdentifiers: identifiers)
+        let observable = Observable<[Peripheral]>.deferred { [weak self] in
+            guard let strongSelf = self else { throw BluetoothError.destroyed }
+            return strongSelf.centralManager.retrievePeripherals(withIdentifiers: identifiers)
                 .map { (peripheralTable: [RxPeripheralType]) ->
                     [Peripheral] in peripheralTable.map {
-                        Peripheral(manager: self, peripheral: $0)
+                        Peripheral(manager: strongSelf, peripheral: $0)
```
Comment (Cierpliwy) [inline Source/BluetoothManager.swift]: Same story here

File: RxBluetoothKit.podspec [hunk 3]
```diff
@@ -20,5 +20,5 @@ Pod::Spec.new do |s|
 
   s.source_files = 'Source/*.swift'
   s.frameworks   = 'CoreBluetooth'
-  s.dependency 'RxSwift', '4.0.0-rc.0'
+  s.dependency 'RxSwift', '4.0.0'
```
Comment (jwhitley) [inline RxBluetoothKit.podspec]: It seems like you'd much rather have a dependency like `s.dependency 'RxSwift', '~> 4.0'`, instead of a hard dependency on `4.0.0`.

Comment (Kacper20) [reply RxBluetoothKit.podspec]: That's right, thank you!
